### ISSUE TITLE
Attachment removed on form modification

### ISSUE THREAD

**Issue by mditure** [Bonitasoft-Community/file-upload-download-example#7]
Hello, when I add other input fields (e.g. Firstname, Lastname ...) on the upload form and:
1) fill the fields (Firstname, Lastname ...);
2) upload some files with "myMultipleDocumentsContract";
3) MODIFY one of the fields at 1);
the uploaded files at 2) disappear and the attachments will not be saved on form submit.
If I don't change any fields, attachments will be saved correctly.
Is it a bug or a mistake?
mdt

**Comment by amottier** [comment]
I try to reproduce your issue but didn't succeed.
Can you maybe share your project (as a .bos file) with your modifications so I can give it a try?

Thanks

**Comment by mditure** [comment]
Hello,
thank you for your answer.
Our project has some connectors to local DBs and forms do not work in your
environment, but I've reproduced the same issue on the
file-upload-download-example.
Here is the .bos file:
https://www.autentitaly.it/tmp/DemoUploadDownloadFileDiagram-1.4.0.bos
Note:
- I use the Business Object "Students";
- I've added the variable formInput on instantiation form;
- I've modified the variable formOutput (on instantiation form) from JSON
to Javascript to include the data inputs.
Thanks

Il giorno gio 19 dic 2019 alle ore 18:22 Antoine Mottier <
notifications@github.com> ha scritto:

**Comment by amottier** [comment]
The issue is not related to the example but to a modification you made.

In fact in your version, `formOutput` variable is a JavaScript expression. This expression will be reevaluated each time a form variable referred in the expression is modified (e.g. `$data.formInput.studentsVarInput` in your example). Based on the current JavaScript code defined for `formOutput` it will set `formOutput.myMultipleDocumentsContract` to null.

As the file upload widget for "Multiple files to upload" is bind to the `formOutput` variable it get emptied each time we edit for example the first name.

My recommendation would be to:

- Use `formInput` to define the initial value of each widgets using JSON variable type.
- Bind widget to `formInput` (don't use `formOutput`).
- Do any processing of data needed before sending them in `formOutput` using JavaScript expression and reference to `formInput` variable only to read the value.
- Associate `formOutput` with the button to submit the form.

If you need more information or help please use the community forum: https://community.bonitasoft.com/questions-and-answers

Thanks

**Comment by mditure** [comment]
Ok, thank you very much.

Il giorno lun 6 gen 2020 alle ore 14:45 Antoine Mottier <
notifications@github.com> ha scritto:
